name: Pipeline Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Instalar Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependências via NPM
      run: npm install

    - name: Execução de testes a nivel da aplicação (Controller neste caso)
      run: npm run test-controller

    - name: Iniciar API Rest
      run: npm start &

    - name: Esperando inicialização da API Rest
      run: sleep 5

    - name: Execução de testes a nivel external via HTTTP
      run: npm run test-external