name: Pipeline Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run software tests
      run: npm run test-controller

    - name: API start
      run: npm start &

    - name: Waiting api starting
      run: sleep 5

    - name: Run software external tests
      run: npm run test-external